name: localnexus
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0  # Add this line
  get: ^4.6.6
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  fl_chart: ^0.66.2
  pdf: ^3.10.8
  path_provider: ^2.1.2
  share_plus: ^6.0.0
  font_awesome_flutter: ^10.2.0  # Added for additional icons