name: localnexus
environment:
  sdk: '>=3.2.0 <4.0.0'

# Configuration options like 'uses-material-design' should be at the root level
flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0
  get: ^4.6.6
  flutter_svg: ^2.0.9
  google_fonts: ^4.0.4
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  fl_chart: ^0.66.2
  pdf: ^3.10.8
  path_provider: ^2.1.2
  share_plus: ^6.0.0
  font_awesome_flutter: ^10.2.0
  flutter_datetime_picker_plus: ^2.0.0
  flutter_riverpod: ^1.0.4
  lucide_icons: ^0.257.0
  timeago: ^3.3.0
  http: ^1.2.0
  file_picker: ^5.2.10
  image_picker: ^1.0.4
  uuid: ^4.0.0
